### ISSUE TITLE
How much space does it require?

### ISSUE THREAD

**Issue by C-Aniruddh** [JetsonHacksNano/rootOnUSB#1]
I am using a 16gb SD Card that I had when I purchased the Nano. As soon as I saw your video, I decided to use a 120gb SSD as the root storage for the Nano. However, the kernel build failed saying no space left on device (this happened on the last step, while copying the Image file). Approximately how much space does the kernel need in case of Jetson Nano?

**Comment by htjain** [comment]
16 GB SD card is not enough to build kernel. To build it requires ~6GB space.
Use following workaround to build it.

1. create one partition of size ~10G on your ssd.
2. mount it and create a soft link to in in /usr/src/ as follows :
    ` ln -s  <mounted path> /usr/src/kernel`
3. run the buildKernel.sh script.
4. reboot and run copyRootToUSB.sh to copy SD card contains to your SSD.
5. make changes in extlinux.conf and reboot. 

Hope it helps good luck.

**Comment by JetsonHacksNano** [comment]
Please use version vL4T32.2.1 for JetPack 4.2.2. The new method can be used with a 16GB SD card.
