### ISSUE TITLE
Install fail: bzip2 unzip error / kernel config fail

### ISSUE THREAD

**Issue by markusmeyerhofer** [JetsonHacksNano/rootOnUSB#3]
Hi - firstly: thank you for providing this!

I tried to install this and ran into a number of issues:

1 - when running ./buildKernel.sh the script fails. Apparently there is an issue with bzip2 on the nano (at least on mine): uncompressing the kernel sources yields an EOF (bzip2: Compressed file end unexpectedly) error. I ran into this error both using the command line as well as GUI (using the file  browser) on 2 distinct installations.
As a workaround I unzipped the kernel sources on my Mac and continued...

2 - make menuconfig fails. Sorry, I am writing this from memory, please bear with me for not being as accurate as I should be here:  as far as I recall it is an issue with a wifi driver which has been removed, but is still referenced somewhere.
I found a couple of comments on Nvidias developer forums confirming the issue, but without providing a solution. 
I also downloaded an allegedly updated kernel but still no luck.

**Comment by JetsonHacksNano** [comment]
Please use version vL4T32.2.1 for JetPack 4.2.2.
