### ISSUE TITLE
RootOnUSB Not working on new Jetpack 4.2 that was release july 19, 2019

### ISSUE THREAD

**Issue by Jay1234578** [JetsonHacksNano/rootOnUSB#5]
After installing the new Jetpack 4.2, it is no long possible to root the jetson nano on a faster USB SSD drive as described on this video on jetson hack.com 

https://www.jetsonhacks.com/2019/04/25/jetson-nano-run-on-usb-drive/

This is the error I got when following the instructions to build the kernal. I Want to confirm that I do have a jetson nano and I had it rooted to run on USB SSD until I decided to upgrade to the new Jetpack 4.2 now suddenly I am getting this "jetson Board Mismatch" issue which is not making any sense.

jetson1@jetson1-desktop:~/rootOnUSB$ ./buildKernel.sh 
Jetson Model: NVIDIA Jetson Nano Developer Kit
Jetson L4T: 
==== Jetson Board Mismatch! =============
Currently this script works for the jetson-nano.
This processor appears to be a NVIDIA Jetson Nano Developer Kit, which does not have a corresponding script

Exiting
jetson1@jetson1-desktop:~/rootOnUSB$ 

Does anyone have the work around for this? HOW can I root my jetson nano to run on USB SSD with Jetpack 4.2?

**Comment by JetsonHacksNano** [comment]
The new version of JetPack is 4.2.1 running L4T 32.2. 
Please see version: 
https://github.com/JetsonHacksNano/rootOnUSB/tree/vL4T32.2
