### ISSUE TITLE
[SOLVED] Jetson-Nano USB SSD dont' move.. please fix it..

### ISSUE THREAD

**Issue by pro2030** [JetsonHacksNano/rootOnUSB#7]
This is the error I got when following the instructions to build the kernal. I Want to confirm that I do have a jetson nano and I had it rooted to run on USB SSD until I decided to upgrade to the new Jetpack 4.2 now suddenly I am getting this "jetson Board Mismatch" issue which is not making any sense.

jetson1@jetson1-desktop:~/rootOnUSB$ ./buildKernel.sh 
Jetson Model: NVIDIA Jetson Nano Developer Kit
Jetson L4T: 
==== Jetson Board Mismatch! =============
Currently this script works for the jetson-nano.
This processor appears to be a NVIDIA Jetson Nano Developer Kit, which does not have a corresponding script

Exiting
jetson1@jetson1-desktop:~/rootOnUSB$ 

4.2.0 old version same error

**Comment by drevocd** [comment]
I have the same problem. Try to use  rootOnUSB-0.8 but it not help to solve the problem.

**Comment by drevocd** [comment]
log for last version:
Getting L4T Version
 Jetson BSP Version:  L4T R32.1.0
Jetson_L4T=32.1.0
==== Jetson Board Mismatch! =============
Currently this script works for the NVIDIA Jetson Nano Developer Kit.
This processor appears to be a jetson-nano, which does not have a corresponding script

Exiting


log for privious versions:
Jetson Model: jetson-nano
Jetson L4T: 32.1.0
Installing buildModulesAndKernel
Cloning into '/home/nano/buildKernelAndModules'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 69 (delta 39), reused 51 (delta 27), pack-reused 0
Unpacking objects: 100% (69/69), done.
Proposed source path: /usr/src/kernel/kernel-4.9
Jetson Model: jetson-nano
Getting L4T Version
 Jetson BSP Version:  L4T R32.1.0
Jetson_L4T=32.1.0
==== Jetson Board Mismatch! =============
Currently this script works for the NVIDIA Jetson Nano Developer Kit.
This processor appears to be a jetson-nano, which does not have a corresponding script

Exiting

**Comment by AITCK** [comment]
same problem +1

**Comment by pro2030** [comment]
[SOLVED] 

1. buildKernel.sh edit open.. and   close download git 

.....
   echo "Installing buildModulesAndKernel"
**#** git clone https://github.com/jetsonhacksnano/buildKernelAndModules/archive/vL4T32.1.zip "$BUILD_REPOSITORY"
.....

2. manualy download
git clone https://github.com/jetsonhacksnano/buildKernelAndModules/archive/vL4T32.1.zip

 extract and folder name fix .... buildKernelAndModules  ( ...-vL4T32.1 delete )

3. buildKernel.sh re-execute ....

ok ...

**Comment by JetsonHacksNano** [comment]
Please use version vL4T32.2.1 for JetPack 4.2.2.
