### ISSUE TITLE
extlinux.conf

### ISSUE THREAD

**Issue by VividDroid** [JetsonHacksNano/rootOnUSB#8]
After modifying extlinux.conf to change boot drive, device(Jetson Nano Developement Board with JetPack 4.2.1 installed) failed to boot fully. USB drivers loaded fine I think, but failed to switch over boot to USB drive. On the previous Jetpack deployment I had 0 issues with switching to usb rootfs. Also by the way cool guitar playing. ) EDIT 8/31/19 Also the build was done on fresh install no updates and a blank usb nvme drive (same equipment used previously)

**Comment by JetsonHacksNano** [comment]
Please use version vL4T32.2.1 for JetPack 4.2.2.
